import { writeFileSync, mkdirSync } from 'node:fs'

mkdirSync('content/lessons/algebra-i-01', { recursive: true })

const L = (en, es, pl) => ({ en, es, pl })
const irt = (b, a = 1) => ({ a, b })
const sr = { initialIntervalDays: 1, easeFactor: 2.5, masteryThreshold: 0.8 }

const stdCore = {
  CCSS: ['CCSS.MATH.CONTENT.6.EE.A.2', 'CCSS.MATH.CONTENT.HSA.SSE.A.1'],
  CA: ['6.EE.2', 'A-SSE.1'],
  NJ: ['6.EE.A.2', 'A-SSE.A.1'],
  MI: ['6.EE.2', 'HSA-SSE.A.1'],
  TX: ['A.1A', 'A.1B'],
  NY: ['AI-A.SSE.1', '6.EE.2'],
  IL: ['6.EE.A.2', 'A-SSE.A.1'],
  MO: ['6.EE.A.2', 'A.SSE.A.1'],
  FL: ['MA.6.AR.1.1', 'MA.912.AR.1.1'],
  WA: ['6.EE.A.2', 'HSA-SSE.A.1'],
  DC: ['6.EE.A.2', 'A-SSE.A.1'],
  OH: ['6.EE.2', 'A.SSE.1'],
  MN: ['6.2.3.1', '9.2.2.1'],
}

const stdEval = {
  CCSS: ['CCSS.MATH.CONTENT.6.EE.A.2.c', 'CCSS.MATH.CONTENT.HSA.SSE.A.1'],
  CA: ['6.EE.2c', 'A-SSE.1'],
  NJ: ['6.EE.A.2c', 'A-SSE.A.1'],
  MI: ['6.EE.2c', 'HSA-SSE.A.1'],
  TX: ['A.1B', 'A.1C'],
  NY: ['AI-A.SSE.1', '6.EE.2c'],
  IL: ['6.EE.A.2c', 'A-SSE.A.1'],
  MO: ['6.EE.A.2c', 'A.SSE.A.1'],
  FL: ['MA.6.AR.1.3', 'MA.912.AR.1.1'],
  WA: ['6.EE.A.2c', 'HSA-SSE.A.1'],
  DC: ['6.EE.A.2c', 'A-SSE.A.1'],
  OH: ['6.EE.2c', 'A.SSE.1'],
  MN: ['6.2.3.2', '9.2.2.1'],
}

const stdEq = {
  CCSS: ['CCSS.MATH.CONTENT.6.EE.B.5', 'CCSS.MATH.CONTENT.HSA.CED.A.1'],
  CA: ['6.EE.5', 'A-CED.1'],
  NJ: ['6.EE.B.5', 'A-CED.A.1'],
  MI: ['6.EE.5', 'HSA-CED.A.1'],
  TX: ['A.1A', 'A.5A'],
  NY: ['AI-A.CED.1', '6.EE.5'],
  IL: ['6.EE.B.5', 'A-CED.A.1'],
  MO: ['6.EE.B.5', 'A.CED.A.1'],
  FL: ['MA.6.AR.2.1', 'MA.912.AR.2.1'],
  WA: ['6.EE.B.5', 'HSA-CED.A.1'],
  DC: ['6.EE.B.5', 'A-CED.A.1'],
  OH: ['6.EE.5', 'A.CED.1'],
  MN: ['6.2.3.3', '9.2.2.2'],
}

function choice(id, en, es, pl, isCorrect, fb, diagnosticTag, latex) {
  return {
    id,
    text: L(en, es, pl),
    isCorrect,
    feedback: L(fb[0], fb[1], fb[2]),
    ...(diagnosticTag ? { diagnosticTag } : {}),
    ...(latex ? { latex } : {}),
  }
}

const pkg = {
  schemaVersion: '1.0.0',
  id: 'algebra-i-01',
  courseId: 'algebra-i',
  order: 1,
  title: L(
    'Variables, Expressions, and the Language of Algebra',
    'Variables, expresiones y el lenguaje del álgebra',
    'Zmienne, wyrażenia i język algebry',
  ),
  objectives: [
    L(
      'Explain what a variable represents.',
      'Explicar qué representa una variable.',
      'Wyjaśnić, co oznacza zmienna.',
    ),
    L(
      'Translate between phrases and algebraic expressions.',
      'Traducir entre frases y expresiones algebraicas.',
      'Tłumaczyć między zwrotami a wyrażeniami algebraicznymi.',
    ),
    L(
      'Evaluate expressions and distinguish them from equations.',
      'Evaluar expresiones y distinguirlas de ecuaciones.',
      'Obliczać wyrażenia i odróżniać je od równań.',
    ),
  ],
  knowledgePointIds: [
    'kp.variable.symbol',
    'kp.translate.phrase-to-expr',
    'kp.eval.expression',
    'kp.distinguish.expr-vs-eq',
    'kp.orderops.with-vars',
  ],
  knowledgePoints: [
    {
      id: 'kp.variable.symbol',
      title: L('Variable as a symbol', 'La variable como símbolo', 'Zmienna jako symbol'),
      description: L(
        'A variable is a symbol (often a letter) that represents a number or quantity that can change.',
        'Una variable es un símbolo (a menudo una letra) que representa un número o cantidad que puede cambiar.',
        'Zmienna to symbol (często litera), który reprezentuje liczbę lub wielkość, która może się zmieniać.',
      ),
      prerequisites: [],
      successCriteria: L(
        'Student can identify variables and state that they stand for numbers that may change.',
        'El estudiante puede identificar variables y afirmar que representan números que pueden cambiar.',
        'Uczeń potrafi wskazać zmienne i stwierdzić, że oznaczają liczby, które mogą się zmieniać.',
      ),
      misconceptions: [
        L(
          'Thinking a variable is always unknown and fixed forever.',
          'Creer que una variable siempre es desconocida y fija.',
          'Myślenie, że zmienna zawsze jest nieznana i stała.',
        ),
      ],
      standards: stdCore,
      irtPriors: irt(-1.2),
      srDefaults: sr,
    },
    {
      id: 'kp.translate.phrase-to-expr',
      title: L(
        'Translate phrases to expressions',
        'Traducir frases a expresiones',
        'Tłumaczenie zwrotów na wyrażenia',
      ),
      description: L(
        'Map words like sum, difference, product, quotient to +, -, ×, ÷ with variables.',
        'Relacionar palabras como suma, diferencia, producto, cociente con +, -, ×, ÷ y variables.',
        'Mapować słowa jak suma, różnica, iloczyn, iloraz na +, -, ×, ÷ ze zmiennymi.',
      ),
      prerequisites: ['kp.variable.symbol'],
      successCriteria: L(
        'Student translates simple phrases both directions with correct operations.',
        'El estudiante traduce frases simples en ambas direcciones con operaciones correctas.',
        'Uczeń tłumaczy proste zwroty w obie strony z poprawnymi działaniami.',
      ),
      misconceptions: [
        L(
          'Reversing subtraction or division order.',
          'Invertir el orden de resta o división.',
          'Odwracanie kolejności odejmowania lub dzielenia.',
        ),
      ],
      standards: stdCore,
      irtPriors: irt(-0.4),
      srDefaults: sr,
    },
    {
      id: 'kp.eval.expression',
      title: L('Evaluate expressions', 'Evaluar expresiones', 'Obliczanie wyrażeń'),
      description: L(
        'Substitute given values for variables and compute the value of an expression.',
        'Sustituir valores dados por variables y calcular el valor de una expresión.',
        'Podstawiać dane wartości za zmienne i obliczać wartość wyrażenia.',
      ),
      prerequisites: ['kp.variable.symbol', 'kp.orderops.with-vars'],
      successCriteria: L(
        'Student correctly evaluates multi-step expressions with substitution.',
        'El estudiante evalúa correctamente expresiones de varios pasos con sustitución.',
        'Uczeń poprawnie oblicza wieloetapowe wyrażenia z podstawieniem.',
      ),
      misconceptions: [
        L(
          'Forgetting order of operations after substituting.',
          'Olvidar el orden de operaciones tras sustituir.',
          'Zapominanie kolejności działań po podstawieniu.',
        ),
      ],
      standards: stdEval,
      irtPriors: irt(0.1),
      srDefaults: sr,
    },
    {
      id: 'kp.distinguish.expr-vs-eq',
      title: L(
        'Expressions vs equations',
        'Expresiones frente a ecuaciones',
        'Wyrażenia a równania',
      ),
      description: L(
        'An expression names a value; an equation asserts equality between two expressions.',
        'Una expresión nombra un valor; una ecuación afirma igualdad entre dos expresiones.',
        'Wyrażenie nazywa wartość; równanie stwierdza równość dwóch wyrażeń.',
      ),
      prerequisites: ['kp.variable.symbol'],
      successCriteria: L(
        'Student correctly classifies expressions vs equations and explains why.',
        'El estudiante clasifica correctamente expresiones vs ecuaciones y explica por qué.',
        'Uczeń poprawnie klasyfikuje wyrażenia vs równania i wyjaśnia dlaczego.',
      ),
      misconceptions: [
        L(
          'Calling any string with a letter an equation.',
          'Llamar ecuación a cualquier cadena con una letra.',
          'Nazywanie równaniem każdego ciągu z literą.',
        ),
      ],
      standards: stdEq,
      irtPriors: irt(-0.8),
      srDefaults: sr,
    },
    {
      id: 'kp.orderops.with-vars',
      title: L(
        'Order of operations with variables',
        'Orden de operaciones con variables',
        'Kolejność działań ze zmiennymi',
      ),
      description: L(
        'Apply order of operations after substituting values into expressions with variables.',
        'Aplicar el orden de operaciones tras sustituir valores en expresiones con variables.',
        'Stosować kolejność działań po podstawieniu wartości do wyrażeń ze zmiennymi.',
      ),
      prerequisites: ['kp.variable.symbol'],
      successCriteria: L(
        'Student evaluates expressions respecting parentheses, exponents, MD, AS.',
        'El estudiante evalúa respetando paréntesis, exponentes, MD y AS.',
        'Uczeń oblicza z poszanowaniem nawiasów, potęg, MD i AS.',
      ),
      misconceptions: [
        L(
          'Always computing left-to-right ignoring multiplication precedence.',
          'Calcular siempre de izquierda a derecha ignorando la multiplicación.',
          'Zawsze od lewej do prawej, ignorując pierwszeństwo mnożenia.',
        ),
      ],
      standards: stdEval,
      irtPriors: irt(0.0),
      srDefaults: sr,
    },
  ],
  phases: [
    {
      id: 'phase.objectives',
      kind: 'objectives',
      title: L('Mission briefing', 'Informe de misión', 'Briefing misji'),
      body: L(
        'Success criteria: identify variables, translate phrases, evaluate expressions, and tell expressions from equations. Mastery unlocks a blueprint pad, Riser Initiate rank, and Zone Beta.',
        'Criterios de éxito: identificar variables, traducir frases, evaluar expresiones y distinguir expresiones de ecuaciones. El dominio desbloquea un plano, rango Iniciado y Zona Beta.',
        'Kryteria sukcesu: wskazywać zmienne, tłumaczyć zwroty, obliczać wyrażenia i odróżniać je od równań. Mistrzostwo odblokowuje plan, rangę Inicjata i Strefę Beta.',
      ),
      bodyLatex: ['x', '3x + 2', '3x + 2 = 11'],
      itemIds: [],
      tutorScript: L(
        'Welcome, Riser. Today you learn the language that powers Compact tech: algebra.',
        'Bienvenido, Ascendente. Hoy aprendes el lenguaje que alimenta la tecnología del Compacto: el álgebra.',
        'Witaj, Wznoszący. Dziś uczysz się języka, który napędza technologię Kompaktu: algebry.',
      ),
    },
    {
      id: 'phase.i_do',
      kind: 'i_do',
      title: L('I do — watch the model', 'Yo hago — observa el modelo', 'Ja robię — obserwuj model'),
      body: L(
        'A variable is a letter standing for a number that can change. The phrase "3 more than twice a number n" becomes 2n+3. An expression has no equals sign; an equation does.',
        'Una variable es una letra que representa un número que puede cambiar. La frase "3 más que el doble de un número n" se convierte en 2n+3. Una expresión no tiene signo igual; una ecuación sí.',
        'Zmienna to litera oznaczająca liczbę, która może się zmieniać. Zwrot "o 3 więcej niż podwojona liczba n" to 2n+3. Wyrażenie nie ma znaku równości; równanie ma.',
      ),
      bodyLatex: ['n', '2n + 3', '2n + 3 = 11'],
      itemIds: ['item.ido.1', 'item.ido.2'],
      tutorScript: L(
        'Watch: I replace words with symbols, then evaluate when a value is given. I never invent an equals sign unless the problem states equality.',
        'Observa: reemplazo palabras por símbolos y luego evalúo si dan un valor. Nunca invento un signo igual si el problema no afirma igualdad.',
        'Patrz: zamieniam słowa na symbole, potem obliczam, gdy podano wartość. Nie dodaję znaku równości, jeśli zadanie nie stwierdza równości.',
      ),
    },
    {
      id: 'phase.we_do',
      kind: 'we_do',
      title: L('We do — guided practice', 'Hacemos — práctica guiada', 'Robimy — ćwiczenia z prowadzeniem'),
      body: L(
        'Answer with me. Use the feedback to correct misconceptions immediately.',
        'Responde conmigo. Usa la retroalimentación para corregir errores de inmediato.',
        'Odpowiadaj ze mną. Użyj informacji zwrotnej, by od razu poprawić błędy.',
      ),
      itemIds: ['item.wedo.1', 'item.wedo.2', 'item.wedo.3', 'item.wedo.4'],
      tutorScript: L(
        'Your turn with support. Say or type the expression, then we check together.',
        'Tu turno con apoyo. Di o escribe la expresión; luego comprobamos juntos.',
        'Twoja kolej ze wsparciem. Powiedz lub wpisz wyrażenie, potem sprawdzimy razem.',
      ),
    },
    {
      id: 'phase.you_do',
      kind: 'you_do',
      title: L('You do — mastery check', 'Tú haces — comprobación de dominio', 'Ty robisz — sprawdzian mistrzostwa'),
      body: L(
        'Independent set. Mastery requires at least 3 of 4 correct.',
        'Serie independiente. El dominio exige al menos 3 de 4 correctas.',
        'Zestaw samodzielny. Mistrzostwo wymaga co najmniej 3 z 4 poprawnych.',
      ),
      itemIds: ['item.youdo.1', 'item.youdo.2', 'item.youdo.3', 'item.youdo.4'],
      tutorScript: L(
        'Show what you know. No hints beyond the success criteria.',
        'Demuestra lo que sabes. Sin pistas más allá de los criterios de éxito.',
        'Pokaż, co umiesz. Bez podpowiedzi poza kryteriami sukcesu.',
      ),
    },
    {
      id: 'phase.retrieval',
      kind: 'retrieval',
      title: L('Quick retrieval', 'Recuperación rápida', 'Szybkie przypomnienie'),
      body: L(
        'Short arithmetic check that supports evaluation.',
        'Breve comprobación aritmética que apoya la evaluación.',
        'Krótki test arytmetyczny wspierający obliczanie.',
      ),
      itemIds: ['item.retr.1', 'item.retr.2'],
      tutorScript: L(
        'Keep fluency warm — Compact systems hate rusty arithmetic.',
        'Mantén la fluidez — a los sistemas del Compacto no les gusta la aritmética oxidada.',
        'Utrzymaj biegłość — systemy Kompaktu nie lubią zardzewiałej arytmetyki.',
      ),
    },
    {
      id: 'phase.complete',
      kind: 'complete',
      title: L('Rank advanced', 'Rango avanzado', 'Awans rangi'),
      body: L(
        'Lesson complete. Place your blueprint pad and access Zone Beta.',
        'Lección completa. Coloca tu plano y accede a la Zona Beta.',
        'Lekcja ukończona. Umieść swój plan i wejdź do Strefy Beta.',
      ),
      itemIds: [],
      tutorScript: L(
        'Well earned, Initiate. Build something worthy of the Compact.',
        'Bien ganado, Iniciado. Construye algo digno del Compacto.',
        'Zasłużone, Inicjacie. Zbuduj coś godnego Kompaktu.',
      ),
    },
  ],
  items: [],
  mastery: {
    minIndependentCorrect: 3,
    minIndependentTotal: 4,
    requiredKpIds: [
      'kp.variable.symbol',
      'kp.translate.phrase-to-expr',
      'kp.eval.expression',
      'kp.distinguish.expr-vs-eq',
      'kp.orderops.with-vars',
    ],
  },
  unlocks: [
    {
      id: 'bp.pad.ramp',
      kind: 'blueprint',
      title: L('Pad / ramp blueprint', 'Plano de plataforma / rampa', 'Plan platformy / rampy'),
      description: L(
        'Place a training pad segment on Zone Alpha.',
        'Coloca un segmento de plataforma en la Zona Alfa.',
        'Umieść segment platformy w Strefie Alfa.',
      ),
    },
    {
      id: 'rank.riser.initiate',
      kind: 'rank',
      title: L('Riser Initiate', 'Ascendente Iniciado', 'Wznoszący Inicjat'),
      description: L(
        'Rank insignia earned by Lesson 1 mastery.',
        'Insignia de rango por dominio de la Lección 1.',
        'Odznaka rangi za mistrzostwo Lekcji 1.',
      ),
    },
    {
      id: 'zone.pad.beta',
      kind: 'zone',
      title: L('Zone Beta', 'Zona Beta', 'Strefa Beta'),
      description: L(
        'Access the second training pad.',
        'Accede a la segunda plataforma de entrenamiento.',
        'Dostęp do drugiej platformy treningowej.',
      ),
    },
  ],
  worldIntegration: {
    terminalId: 'terminal.lesson1',
    unlockBlueprintId: 'bp.pad.ramp',
    unlockRankId: 'rank.riser.initiate',
    unlockZoneId: 'zone.pad.beta',
  },
}

pkg.items = [
  {
    id: 'item.ido.1',
    kpIds: ['kp.variable.symbol'],
    phase: 'i_do',
    type: 'mcq',
    stem: L(
      'In the expression 4y + 1, what does y represent?',
      'En la expresión 4y + 1, ¿qué representa y?',
      'W wyrażeniu 4y + 1, co oznacza y?',
    ),
    stemLatex: '4y + 1',
    choices: [
      choice(
        'a',
        'A fixed decoration',
        'Un adorno fijo',
        'Stała ozdoba',
        false,
        [
          'y stands for a number that can change.',
          'y representa un número que puede cambiar.',
          'y oznacza liczbę, która może się zmieniać.',
        ],
        'label-only',
      ),
      choice(
        'b',
        'A number that can change',
        'Un número que puede cambiar',
        'Liczbę, która może się zmieniać',
        true,
        ['Correct — y is a variable.', 'Correcto — y es una variable.', 'Poprawnie — y jest zmienną.'],
      ),
      choice(
        'c',
        'Always equal to 4',
        'Siempre igual a 4',
        'Zawsze równe 4',
        false,
        [
          '4 is the coefficient; y can take other values.',
          '4 es el coeficiente; y puede tomar otros valores.',
          '4 to współczynnik; y może przyjąć inne wartości.',
        ],
        'coeff-confuse',
      ),
    ],
    workedSolution: L(
      'y is a variable: a symbol for a number that may change.',
      'y es una variable: un símbolo de un número que puede cambiar.',
      'y jest zmienną: symbolem liczby, która może się zmieniać.',
    ),
    standards: stdCore,
    irtPriors: irt(-1.0),
    difficulty: 'intro',
  },
  {
    id: 'item.ido.2',
    kpIds: ['kp.translate.phrase-to-expr', 'kp.distinguish.expr-vs-eq'],
    phase: 'i_do',
    type: 'mcq',
    stem: L(
      'Which is an expression (not an equation) for "5 less than a number x"?',
      '¿Cuál es una expresión (no ecuación) para "5 menos que un número x"?',
      'Które jest wyrażeniem (nie równaniem) dla "o 5 mniej niż liczba x"?',
    ),
    choices: [
      choice(
        'a',
        'x - 5 = 0',
        'x - 5 = 0',
        'x - 5 = 0',
        false,
        [
          'Has an equals sign — that is an equation.',
          'Tiene signo igual — es una ecuación.',
          'Ma znak równości — to równanie.',
        ],
        'eq-vs-expr',
        'x - 5 = 0',
      ),
      choice(
        'b',
        'x - 5',
        'x - 5',
        'x - 5',
        true,
        ['Correct — no equals sign.', 'Correcto — sin signo igual.', 'Poprawnie — bez znaku równości.'],
        undefined,
        'x - 5',
      ),
      choice(
        'c',
        '5 - x = 5',
        '5 - x = 5',
        '5 - x = 5',
        false,
        [
          'Wrong order and it is an equation.',
          'Orden incorrecto y es una ecuación.',
          'Zła kolejność i to równanie.',
        ],
        'reversed',
        '5 - x = 5',
      ),
    ],
    workedSolution: L(
      '"5 less than x" is x-5, an expression.',
      '"5 menos que x" es x-5, una expresión.',
      '"o 5 mniej niż x" to x-5, wyrażenie.',
    ),
    workedSolutionLatex: 'x - 5',
    standards: stdCore,
    irtPriors: irt(-0.5),
    difficulty: 'intro',
  },
  {
    id: 'item.wedo.1',
    kpIds: ['kp.translate.phrase-to-expr'],
    phase: 'we_do',
    type: 'translate',
    stem: L(
      'Translate: "the sum of a number n and 7".',
      'Traduce: "la suma de un número n y 7".',
      'Przetłumacz: "suma liczby n i 7".',
    ),
    answer: 'n+7',
    acceptableAnswers: ['n+7', 'n + 7', '7+n', '7 + n'],
    workedSolution: L(
      'Sum means +; write n+7.',
      'Suma significa +; escribe n+7.',
      'Suma oznacza +; napisz n+7.',
    ),
    workedSolutionLatex: 'n + 7',
    standards: stdCore,
    irtPriors: irt(-0.3),
    difficulty: 'guided',
    choices: [
      choice(
        'a',
        'n + 7',
        'n + 7',
        'n + 7',
        true,
        ['Yes — sum is addition.', 'Sí — suma es adición.', 'Tak — suma to dodawanie.'],
        undefined,
        'n + 7',
      ),
      choice(
        'b',
        'n - 7',
        'n - 7',
        'n - 7',
        false,
        ['Sum is +, not −.', 'Suma es +, no −.', 'Suma to +, nie −.'],
        'op-wrong',
        'n - 7',
      ),
      choice(
        'c',
        '7n',
        '7n',
        '7n',
        false,
        [
          'That is a product, not a sum.',
          'Eso es un producto, no una suma.',
          'To iloczyn, nie suma.',
        ],
        'product',
        '7n',
      ),
      choice(
        'd',
        'n + 7 = 0',
        'n + 7 = 0',
        'n + 7 = 0',
        false,
        [
          'Do not add an equals sign.',
          'No añadas un signo igual.',
          'Nie dodawaj znaku równości.',
        ],
        'eq-extra',
        'n + 7 = 0',
      ),
    ],
  },
  {
    id: 'item.wedo.2',
    kpIds: ['kp.eval.expression', 'kp.orderops.with-vars'],
    phase: 'we_do',
    type: 'evaluate',
    stem: L(
      'Evaluate 2x + 3 when x = 4.',
      'Evalúa 2x + 3 cuando x = 4.',
      'Oblicz 2x + 3, gdy x = 4.',
    ),
    stemLatex: '2x + 3,\\; x = 4',
    answer: '11',
    acceptableAnswers: ['11'],
    workedSolution: L(
      'Substitute: 2(4)+3 = 8+3 = 11.',
      'Sustituye: 2(4)+3 = 8+3 = 11.',
      'Podstaw: 2(4)+3 = 8+3 = 11.',
    ),
    workedSolutionLatex: '2(4) + 3 = 11',
    standards: stdEval,
    irtPriors: irt(0.0),
    difficulty: 'guided',
    choices: [
      choice('a', '11', '11', '11', true, ['Correct.', 'Correcto.', 'Poprawnie.']),
      choice(
        'b',
        '14',
        '14',
        '14',
        false,
        [
          'You may have done 2+4 first then times 3.',
          'Quizá hiciste 2+4 y luego por 3.',
          'Możliwe, że najpierw 2+4, potem razy 3.',
        ],
        'order-ops',
      ),
      choice(
        'c',
        '24',
        '24',
        '24',
        false,
        ['Check the product carefully.', 'Revisa el producto.', 'Sprawdź iloczyn.'],
        'concat',
      ),
      choice(
        'd',
        '9',
        '9',
        '9',
        false,
        ['Check 2 times 4 again.', 'Revisa 2 por 4.', 'Sprawdź 2 razy 4.'],
        'arith',
      ),
    ],
  },
  {
    id: 'item.wedo.3',
    kpIds: ['kp.distinguish.expr-vs-eq'],
    phase: 'we_do',
    type: 'mcq',
    stem: L(
      'Which of these is an equation?',
      '¿Cuál de estos es una ecuación?',
      'Które z tych jest równaniem?',
    ),
    choices: [
      choice(
        'a',
        '3a + 2',
        '3a + 2',
        '3a + 2',
        false,
        [
          'No equals sign — expression.',
          'Sin signo igual — expresión.',
          'Bez znaku równości — wyrażenie.',
        ],
        'expr',
        '3a + 2',
      ),
      choice(
        'b',
        '3a + 2 = 14',
        '3a + 2 = 14',
        '3a + 2 = 14',
        true,
        [
          'Equals sign asserts equality.',
          'El signo igual afirma igualdad.',
          'Znak równości stwierdza równość.',
        ],
        undefined,
        '3a + 2 = 14',
      ),
      choice(
        'c',
        'a',
        'a',
        'a',
        false,
        [
          'Just a variable symbol.',
          'Solo un símbolo de variable.',
          'Sam symbol zmiennej.',
        ],
        'var',
      ),
    ],
    workedSolution: L(
      'Equations contain =.',
      'Las ecuaciones contienen =.',
      'Równania zawierają =.',
    ),
    standards: stdEq,
    irtPriors: irt(-0.6),
    difficulty: 'guided',
  },
  {
    id: 'item.wedo.4',
    kpIds: ['kp.translate.phrase-to-expr'],
    phase: 'we_do',
    type: 'short',
    stem: L(
      'Write an expression for "twice a number m".',
      'Escribe una expresión para "el doble de un número m".',
      'Napisz wyrażenie dla "podwojona liczba m".',
    ),
    answer: '2m',
    acceptableAnswers: ['2m', '2*m', '2 m', 'm*2', 'm2'],
    workedSolution: L(
      'Twice means multiply by 2: 2m.',
      'El doble es multiplicar por 2: 2m.',
      'Podwojona oznacza mnożenie przez 2: 2m.',
    ),
    workedSolutionLatex: '2m',
    standards: stdCore,
    irtPriors: irt(-0.2),
    difficulty: 'guided',
  },
  {
    id: 'item.youdo.1',
    kpIds: ['kp.variable.symbol'],
    phase: 'you_do',
    type: 'mcq',
    stem: L(
      'Why do engineers in the Compact use variables in blueprints?',
      '¿Por qué los ingenieros del Compacto usan variables en los planos?',
      'Dlaczego inżynierowie Kompaktu używają zmiennych w planach?',
    ),
    choices: [
      choice(
        'a',
        'To represent quantities that can take different values',
        'Para representar cantidades que pueden tomar distintos valores',
        'Aby reprezentować wielkości o różnych wartościach',
        true,
        ['Exactly.', 'Exacto.', 'Dokładnie.'],
      ),
      choice(
        'b',
        'To decorate formulas',
        'Para decorar fórmulas',
        'Aby ozdobić wzory',
        false,
        [
          'Variables carry meaning, not decoration.',
          'Las variables tienen significado, no decoración.',
          'Zmienne mają znaczenie, nie są ozdobą.',
        ],
        'decor',
      ),
      choice(
        'c',
        'Because letters are prettier than numbers',
        'Porque las letras son más bonitas',
        'Bo litery są ładniejsze',
        false,
        ['Utility, not aesthetics.', 'Utilidad, no estética.', 'Użyteczność, nie estetyka.'],
        'aesthetic',
      ),
    ],
    workedSolution: L(
      'Variables stand for changeable quantities.',
      'Las variables representan cantidades cambiantes.',
      'Zmienne oznaczają zmienne wielkości.',
    ),
    standards: stdCore,
    irtPriors: irt(-0.7),
    difficulty: 'independent',
  },
  {
    id: 'item.youdo.2',
    kpIds: ['kp.translate.phrase-to-expr'],
    phase: 'you_do',
    type: 'mcq',
    stem: L(
      'Which expression matches "8 more than a number t"?',
      '¿Qué expresión corresponde a "8 más que un número t"?',
      'Które wyrażenie odpowiada "o 8 więcej niż liczba t"?',
    ),
    choices: [
      choice(
        'a',
        '8t',
        '8t',
        '8t',
        false,
        ['That is 8 times t.', 'Eso es 8 veces t.', 'To 8 razy t.'],
        'product',
        '8t',
      ),
      choice(
        'b',
        't + 8',
        't + 8',
        't + 8',
        true,
        ['More than means add.', 'Más que significa sumar.', 'Więcej niż oznacza dodawanie.'],
        undefined,
        't + 8',
      ),
      choice(
        'c',
        't - 8',
        't - 8',
        't - 8',
        false,
        ['That is 8 less than t.', 'Eso es 8 menos que t.', 'To o 8 mniej niż t.'],
        'less',
        't - 8',
      ),
      choice(
        'd',
        't + 8 = 8',
        't + 8 = 8',
        't + 8 = 8',
        false,
        ['Equation, not expression.', 'Ecuación, no expresión.', 'Równanie, nie wyrażenie.'],
        'eq',
        't + 8 = 8',
      ),
    ],
    workedSolution: L(
      '"8 more than t" maps to t+8.',
      '"8 más que t" corresponde a t+8.',
      '"o 8 więcej niż t" to t+8.',
    ),
    standards: stdCore,
    irtPriors: irt(0.1),
    difficulty: 'independent',
  },
  {
    id: 'item.youdo.3',
    kpIds: ['kp.eval.expression', 'kp.orderops.with-vars'],
    phase: 'you_do',
    type: 'evaluate',
    stem: L(
      'Evaluate 5 + 3k when k = 2.',
      'Evalúa 5 + 3k cuando k = 2.',
      'Oblicz 5 + 3k, gdy k = 2.',
    ),
    stemLatex: '5 + 3k,\\; k = 2',
    answer: '11',
    acceptableAnswers: ['11'],
    workedSolution: L(
      '5 + 3(2) = 5 + 6 = 11.',
      '5 + 3(2) = 5 + 6 = 11.',
      '5 + 3(2) = 5 + 6 = 11.',
    ),
    workedSolutionLatex: '5 + 3(2) = 11',
    standards: stdEval,
    irtPriors: irt(0.2),
    difficulty: 'independent',
    choices: [
      choice('a', '11', '11', '11', true, ['Correct.', 'Correcto.', 'Poprawnie.']),
      choice(
        'b',
        '16',
        '16',
        '16',
        false,
        [
          '(5+3)*2 is wrong order.',
          '(5+3)*2 es orden incorrecto.',
          '(5+3)*2 to zła kolejność.',
        ],
        'order',
      ),
      choice(
        'c',
        '10',
        '10',
        '10',
        false,
        ['You may have done 5+3+2.', 'Quizá hiciste 5+3+2.', 'Możliwe 5+3+2.'],
        'add-all',
      ),
      choice(
        'd',
        '7',
        '7',
        '7',
        false,
        [
          'Multiply 3*2 first, then add 5.',
          'Multiplica 3*2 primero, luego suma 5.',
          'Najpierw 3*2, potem +5.',
        ],
        'partial',
      ),
    ],
  },
  {
    id: 'item.youdo.4',
    kpIds: ['kp.distinguish.expr-vs-eq', 'kp.translate.phrase-to-expr'],
    phase: 'you_do',
    type: 'short',
    stem: L(
      'Type an expression (not equation) for "the product of 4 and w".',
      'Escribe una expresión (no ecuación) para "el producto de 4 y w".',
      'Wpisz wyrażenie (nie równanie) dla "iloczyn 4 i w".',
    ),
    answer: '4w',
    acceptableAnswers: ['4w', '4*w', '4 w', 'w*4', 'w4'],
    workedSolution: L(
      'Product means multiply: 4w. No equals sign.',
      'Producto significa multiplicar: 4w. Sin signo igual.',
      'Iloczyn oznacza mnożenie: 4w. Bez znaku równości.',
    ),
    workedSolutionLatex: '4w',
    standards: stdCore,
    irtPriors: irt(0.0),
    difficulty: 'independent',
  },
  {
    id: 'item.retr.1',
    kpIds: ['kp.orderops.with-vars'],
    phase: 'retrieval',
    type: 'evaluate',
    stem: L('Compute 3 × 4 + 2.', 'Calcula 3 × 4 + 2.', 'Oblicz 3 × 4 + 2.'),
    stemLatex: '3 \\times 4 + 2',
    answer: '14',
    acceptableAnswers: ['14'],
    workedSolution: L(
      'Multiply first: 12 + 2 = 14.',
      'Multiplica primero: 12 + 2 = 14.',
      'Najpierw mnożenie: 12 + 2 = 14.',
    ),
    standards: stdEval,
    irtPriors: irt(-1.5),
    difficulty: 'intro',
    choices: [
      choice('a', '14', '14', '14', true, ['Correct.', 'Correcto.', 'Poprawnie.']),
      choice(
        'b',
        '18',
        '18',
        '18',
        false,
        [
          'Left-to-right without precedence.',
          'Izquierda a derecha sin precedencia.',
          'Od lewej bez pierwszeństwa.',
        ],
        'ltr',
      ),
    ],
  },
  {
    id: 'item.retr.2',
    kpIds: ['kp.eval.expression'],
    phase: 'retrieval',
    type: 'evaluate',
    stem: L(
      'If p = 5, what is p + p?',
      'Si p = 5, ¿cuánto es p + p?',
      'Jeśli p = 5, ile wynosi p + p?',
    ),
    stemLatex: 'p + p,\\; p = 5',
    answer: '10',
    acceptableAnswers: ['10'],
    workedSolution: L('5 + 5 = 10.', '5 + 5 = 10.', '5 + 5 = 10.'),
    standards: stdEval,
    irtPriors: irt(-1.8),
    difficulty: 'intro',
    choices: [
      choice('a', '10', '10', '10', true, ['Correct.', 'Correcto.', 'Poprawnie.']),
      choice(
        'b',
        '25',
        '25',
        '25',
        false,
        ['That is p times p.', 'Eso es p por p.', 'To p razy p.'],
        'square',
      ),
    ],
  },
]

writeFileSync('content/lessons/algebra-i-01/package.json', JSON.stringify(pkg, null, 2))
console.log('Wrote lesson package', pkg.items.length, 'items')
