/**
 * Wave 26 — emit algebra-i-06 (variables on both sides).
 * Run: npx tsx scripts/gen-lesson6-wave26.ts
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const outPath = join(__dirname, '../content/lessons/algebra-i-06/package.json')

const L = (en: string, es: string, pl: string) => ({ en, es, pl })

const stdBoth = {
  CCSS: ['CCSS.MATH.CONTENT.8.EE.C.7'],
  CA: ['8.EE.7'],
  NJ: ['8.EE.C.7'],
  MI: ['8.EE.7'],
  TX: ['A.5A', '8.8C'],
  NY: ['8.EE.7'],
  IL: ['8.EE.C.7'],
  MO: ['8.EE.C.7'],
  FL: ['MA.8.AR.2.1', 'MA.8.AR.2.3'],
  WA: ['8.EE.C.7'],
  DC: ['8.EE.C.7'],
  OH: ['8.EE.7'],
  MN: ['8.2.4.6'],
}

const stdVerify = {
  CCSS: ['CCSS.MATH.CONTENT.6.EE.B.5', 'CCSS.MATH.CONTENT.8.EE.C.7'],
  CA: ['6.EE.5', '8.EE.7'],
  NJ: ['6.EE.B.5', '8.EE.C.7'],
  MI: ['6.EE.5', '8.EE.7'],
  TX: ['6.10B', 'A.5A'],
  NY: ['6.EE.5', '8.EE.7'],
  IL: ['6.EE.B.5', '8.EE.C.7'],
  MO: ['6.EE.B.5', '8.EE.C.7'],
  FL: ['MA.6.AR.2.3', 'MA.8.AR.2.1'],
  WA: ['6.EE.B.5', '8.EE.C.7'],
  DC: ['6.EE.B.5', '8.EE.C.7'],
  OH: ['6.EE.5', '8.EE.7'],
  MN: ['6.2.3.3', '8.2.4.6'],
}

const sr = { initialIntervalDays: 1, easeFactor: 2.5, masteryThreshold: 0.8 }

function choice(
  id: string,
  latex: string,
  correct: boolean,
  tag: string | undefined,
  fb: ReturnType<typeof L>,
) {
  return {
    id,
    text: L(latex, latex, latex),
    latex,
    isCorrect: correct,
    ...(tag ? { diagnosticTag: tag } : {}),
    feedback: fb,
  }
}

const pkg = {
  schemaVersion: '1.0.0',
  id: 'algebra-i-06',
  courseId: 'algebra-i',
  order: 6,
  title: L(
    'Equations with Variables on Both Sides',
    'Ecuaciones con variables en ambos lados',
    'Równania ze zmiennymi po obu stronach',
  ),
  objectives: [
    L(
      'Collect variable terms onto one side of an equation of the form ax + b = cx + d.',
      'Reunir los términos con variable en un lado de una ecuación de la forma ax + b = cx + d.',
      'Zebrać wyrazy ze zmienną po jednej stronie równania postaci ax + b = cx + d.',
    ),
    L(
      'Finish isolating the variable after collecting like terms across the equals sign.',
      'Terminar de despejar la variable después de reunir términos semejantes a través del signo igual.',
      'Dokończyć izolowanie zmiennej po zebraniu wyrazów podobnych po obu stronach równości.',
    ),
    L(
      'Handle signed coefficients when variables appear on both sides, and verify solutions by substitution.',
      'Manejar coeficientes con signo cuando hay variables en ambos lados, y verificar por sustitución.',
      'Obsługiwać współczynniki ze znakiem przy zmiennych po obu stronach i weryfikować przez podstawienie.',
    ),
  ],
  knowledgePointIds: [
    'kp.equation.both-sides-collect',
    'kp.equation.both-sides-isolate',
    'kp.equation.both-sides-signed',
    'kp.equation.both-sides-verify',
  ],
  knowledgePoints: [
    {
      id: 'kp.equation.both-sides-collect',
      title: L(
        'Move variable terms to one side',
        'Mover términos con variable a un lado',
        'Przenieś wyrazy ze zmienną na jedną stronę',
      ),
      description: L(
        'For ax + b = cx + d, subtract cx (or ax) from both sides so all variable terms sit on one side.',
        'Para ax + b = cx + d, resta cx (o ax) en ambos lados para que todos los términos con variable queden de un lado.',
        'Dla ax + b = cx + d odejmij cx (lub ax) po obu stronach, aby wszystkie wyrazy ze zmienną były po jednej stronie.',
      ),
      prerequisites: ['algebra-i-05:kp.equation.two-step-mult-then-add'],
      successCriteria: L(
        'Student correctly moves variable terms across the equals sign without dropping signs.',
        'El estudiante mueve correctamente los términos con variable a través del igual sin perder signos.',
        'Uczeń poprawnie przenosi wyrazy ze zmienną przez znak równości bez gubienia znaków.',
      ),
      misconceptions: [
        L(
          'Adding variable terms from both sides instead of subtracting (wrong side / wrong inverse).',
          'Sumar términos con variable de ambos lados en vez de restar (lado incorrecto / inverso incorrecto).',
          'Dodawanie wyrazów ze zmienną z obu stron zamiast odejmowania (zła strona / zła operacja odwrotna).',
        ),
      ],
      standards: stdBoth,
      irtPriors: { a: 1, b: -0.2 },
      srDefaults: sr,
    },
    {
      id: 'kp.equation.both-sides-isolate',
      title: L(
        'Isolate after collecting both sides',
        'Despejar después de reunir ambos lados',
        'Izoluj po zebraniu obu stron',
      ),
      description: L(
        'After variables are on one side and constants on the other, finish with one-step or two-step inverse operations.',
        'Después de que las variables estén de un lado y las constantes del otro, termina con operaciones inversas de uno o dos pasos.',
        'Gdy zmienne są po jednej stronie, a stałe po drugiej, dokończ odwrotnymi operacjami jedno- lub dwustopniowymi.',
      ),
      prerequisites: [
        'kp.equation.both-sides-collect',
        'algebra-i-05:kp.equation.two-step-add-then-mult',
      ],
      successCriteria: L(
        'Student finishes isolation after collecting, arriving at the correct solution.',
        'El estudiante termina el despeje después de reunir, llegando a la solución correcta.',
        'Uczeń kończy izolację po zebraniu i dochodzi do poprawnego rozwiązania.',
      ),
      misconceptions: [
        L(
          'Stopping after collecting (partial solve) or dividing before removing the constant.',
          'Detenerse después de reunir (solución parcial) o dividir antes de quitar la constante.',
          'Zatrzymanie się po zebraniu (częściowe rozwiązanie) lub dzielenie przed usunięciem stałej.',
        ),
      ],
      standards: stdBoth,
      irtPriors: { a: 1, b: 0.1 },
      srDefaults: sr,
    },
    {
      id: 'kp.equation.both-sides-signed',
      title: L(
        'Both sides with signed coefficients',
        'Ambos lados con coeficientes con signo',
        'Obie strony ze współczynnikami ze znakiem',
      ),
      description: L(
        'When a coefficient is negative or terms are rearranged, track signs carefully while collecting and isolating.',
        'Cuando un coeficiente es negativo o los términos están reordenados, sigue los signos con cuidado al reunir y despejar.',
        'Gdy współczynnik jest ujemny lub wyrazy są przestawione, uważnie śledź znaki przy zbieraniu i izolowaniu.',
      ),
      prerequisites: [
        'kp.equation.both-sides-isolate',
        'algebra-i-05:kp.equation.two-step-signed',
      ],
      successCriteria: L(
        'Student solves both-sides equations with negatives without sign slips.',
        'El estudiante resuelve ecuaciones de ambos lados con negativos sin errores de signo.',
        'Uczeń rozwiązuje równania obu stron z ujemnymi bez pomyłek znaku.',
      ),
      misconceptions: [
        L(
          'Dropping a negative when subtracting a negative variable term (sign-slip).',
          'Perder un negativo al restar un término con variable negativo (error de signo).',
          'Gubienie minusa przy odejmowaniu ujemnego wyrazu ze zmienną (pomyłka znaku).',
        ),
      ],
      standards: stdBoth,
      irtPriors: { a: 1, b: 0.4 },
      srDefaults: sr,
    },
    {
      id: 'kp.equation.both-sides-verify',
      title: L(
        'Verify both-sides solutions by substitution',
        'Verificar soluciones de ambos lados por sustitución',
        'Weryfikuj rozwiązania obu stron przez podstawienie',
      ),
      description: L(
        'Substitute the candidate solution into both sides of the original equation and confirm both sides match.',
        'Sustituye la solución candidata en ambos lados de la ecuación original y confirma que coinciden.',
        'Podstaw kandydujące rozwiązanie do obu stron oryginalnego równania i potwierdź zgodność.',
      ),
      prerequisites: [
        'kp.equation.both-sides-isolate',
        'algebra-i-05:kp.equation.two-step-verify',
      ],
      successCriteria: L(
        'Student verifies a both-sides solution by showing both sides evaluate equal.',
        'El estudiante verifica una solución de ambos lados mostrando que ambos lados dan lo mismo.',
        'Uczeń weryfikuje rozwiązanie obu stron, pokazując że obie strony dają tę samą wartość.',
      ),
      misconceptions: [
        L(
          'Checking only one side or accepting a value that fails substitution (verify-skip).',
          'Comprobar solo un lado o aceptar un valor que falla la sustitución (omitir verificación).',
          'Sprawdzanie tylko jednej strony lub akceptowanie wartości, która nie przechodzi podstawienia.',
        ),
      ],
      standards: stdVerify,
      irtPriors: { a: 1, b: 0.6 },
      srDefaults: sr,
    },
  ],
  phases: [
    {
      id: 'phase.objectives',
      kind: 'objectives',
      title: L('Mission briefing', 'Informe de misión', 'Briefing misji'),
      body: L(
        'Variables can sit on both sides of the mirror. Collect them, isolate, and verify — the Zeta Mirror Yard opens when you master the both-sides balance.',
        'Las variables pueden estar en ambos lados del espejo. Reúnelas, despéjalas y verifica — el Patio Espejo Zeta se abre cuando domines el equilibrio de ambos lados.',
        'Zmienne mogą być po obu stronach lustra. Zbierz je, izoluj i zweryfikuj — Dziedziniec Lustra Zeta otworzy się, gdy opanujesz równowagę obu stron.',
      ),
      bodyLatex: ['ax + b = cx + d', '\\text{collect} \\rightarrow \\text{isolate} \\rightarrow \\text{verify}'],
      itemIds: [],
      tutorScript: L(
        'Today we move variable terms across the equals sign, then finish isolation. Watch for sign traps.',
        'Hoy movemos términos con variable a través del igual y luego terminamos el despeje. Cuidado con las trampas de signo.',
        'Dziś przenosimy wyrazy ze zmienną przez znak równości, potem kończymy izolację. Uważaj na pułapki znaków.',
      ),
    },
    {
      id: 'phase.i_do',
      kind: 'i_do',
      title: L('I do — watch the mirror', 'Yo hago — observa el espejo', 'Ja robię — obserwuj lustro'),
      body: L(
        'I will collect variable terms first, then isolate. Follow each inverse step.',
        'Primero reuniré los términos con variable, luego despejaré. Sigue cada paso inverso.',
        'Najpierw zbiorę wyrazy ze zmienną, potem wyizoluję. Śledź każdy krok odwrotny.',
      ),
      bodyLatex: ['2x + 3 = x + 8', '5x - 1 = 2x + 11'],
      itemIds: ['item.ido.1', 'item.ido.2'],
      tutorScript: L(
        'Subtract the smaller variable term from both sides so x stays positive when you can.',
        'Resta el término con variable más pequeño en ambos lados para que x quede positivo cuando puedas.',
        'Odejmij mniejszy wyraz ze zmienną po obu stronach, aby x zostało dodatnie, gdy to możliwe.',
      ),
    },
    {
      id: 'phase.we_do',
      kind: 'we_do',
      title: L('We do — collect together', 'Hacemos juntos — reunimos', 'Robimy razem — zbieramy'),
      body: L(
        'Work with me: collect, isolate, and handle a signed case. Two items are typed.',
        'Trabaja conmigo: reúne, despeja y maneja un caso con signo. Dos ítems son escritos.',
        'Pracuj ze mną: zbierz, izoluj i obsłuż przypadek ze znakiem. Dwa zadania są wpisywane.',
      ),
      bodyLatex: ['3x + 7 = x + 19', '4x - 5 = x + 16'],
      itemIds: ['item.wedo.1', 'item.wedo.2', 'item.wedo.3', 'item.wedo.4'],
      tutorScript: L(
        'Say the inverse out loud before you write it — especially with negatives.',
        'Di el inverso en voz alta antes de escribirlo — especialmente con negativos.',
        'Powiedz operację odwrotną na głos przed zapisaniem — zwłaszcza przy ujemnych.',
      ),
    },
    {
      id: 'phase.you_do',
      kind: 'you_do',
      title: L('You do — independent mirror', 'Tú haces — espejo independiente', 'Ty robisz — samodzielne lustro'),
      body: L(
        'Four independent items. Mastery needs 3 of 4 correct across the required knowledge points.',
        'Cuatro ítems independientes. El dominio requiere 3 de 4 correctos en los puntos de conocimiento requeridos.',
        'Cztery samodzielne zadania. Mistrzostwo wymaga 3 z 4 poprawnych na wymaganych punktach wiedzy.',
      ),
      bodyLatex: ['5x + 2 = 2x + 26', '2x + 5 = x + 14'],
      itemIds: ['item.youdo.1', 'item.youdo.2', 'item.youdo.3', 'item.youdo.4'],
      tutorScript: L(
        'Collect first, then isolate. On the verify item, substitute into both sides.',
        'Reúne primero, luego despeja. En el ítem de verificación, sustituye en ambos lados.',
        'Najpierw zbierz, potem izoluj. Przy weryfikacji podstaw do obu stron.',
      ),
    },
    {
      id: 'phase.retrieval',
      kind: 'retrieval',
      title: L('Retrieval pulse', 'Pulso de recuperación', 'Puls odzyskiwania'),
      body: L(
        'Quick both-sides checks to lock the habit.',
        'Comprobaciones rápidas de ambos lados para fijar el hábito.',
        'Szybkie sprawdzenia obu stron, by utrwalić nawyk.',
      ),
      bodyLatex: ['4x + 1 = 2x + 21'],
      itemIds: ['item.retr.1', 'item.retr.2'],
      tutorScript: L(
        'Same moves, faster. Trust the order: collect, then isolate.',
        'Los mismos movimientos, más rápido. Confía en el orden: reunir, luego despejar.',
        'Te same ruchy, szybciej. Ufaj kolejności: zbierz, potem izoluj.',
      ),
    },
    {
      id: 'phase.complete',
      kind: 'complete',
      title: L('Mirror sealed', 'Espejo sellado', 'Lustro zamknięte'),
      body: L(
        'You can solve equations with variables on both sides. Unlock the mirror blueprint, Vanguard rank, and Zeta Mirror Yard.',
        'Puedes resolver ecuaciones con variables en ambos lados. Desbloquea el plano espejo, el rango Vanguardia y el Patio Espejo Zeta.',
        'Potrafisz rozwiązywać równania ze zmiennymi po obu stronach. Odblokuj plan lustra, rangę Awangardy i Dziedziniec Lustra Zeta.',
      ),
      bodyLatex: ['ax + b = cx + d \\Rightarrow x = \\frac{d - b}{a - c}'],
      itemIds: [],
      tutorScript: L(
        'Outstanding. Next rung: inequalities — but first enjoy the Zeta payoff when the world props land.',
        'Excelente. Siguiente peldaño: desigualdades — pero primero disfruta la recompensa Zeta cuando lleguen los props del mundo.',
        'Świetnie. Następny szczebel: nierówności — ale najpierw ciesz się nagrodą Zeta, gdy pojawią się rekwizyty świata.',
      ),
    },
  ],
  items: [
    {
      id: 'item.ido.1',
      kpIds: ['kp.equation.both-sides-collect'],
      phase: 'i_do',
      type: 'mcq',
      stem: L('Solve: $2x + 3 = x + 8$', 'Resuelve: $2x + 3 = x + 8$', 'Rozwiąż: $2x + 3 = x + 8$'),
      stemLatex: '2x + 3 = x + 8',
      choices: [
        choice('a', 'x = 11', false, 'wrong-side', L('Adding the x terms gives 3x — subtract x from both sides instead.', 'Sumar las x da 3x — resta x en ambos lados.', 'Dodanie x daje 3x — odejmij x po obu stronach.')),
        choice('b', 'x = 5/3', false, 'partial-solve', L('That keeps a fraction after a wrong collect. Subtract x: x + 3 = 8, then x = 5.', 'Eso deja una fracción tras reunir mal. Resta x: x + 3 = 8, luego x = 5.', 'To zostawia ułamek po złym zebraniu. Odejmij x: x + 3 = 8, potem x = 5.')),
        choice('c', 'x = 5', true, undefined, L('Correct: subtract x → x + 3 = 8 → x = 5.', 'Correcto: resta x → x + 3 = 8 → x = 5.', 'Poprawnie: odejmij x → x + 3 = 8 → x = 5.')),
        choice('d', 'x = 8', false, 'wrong-inverse', L('Ignoring the left constant. After x + 3 = 8, subtract 3.', 'Ignoras la constante izquierda. Tras x + 3 = 8, resta 3.', 'Ignorujesz lewą stałą. Po x + 3 = 8 odejmij 3.')),
      ],
      workedSolution: L('Subtract x from both sides: x + 3 = 8. Subtract 3: x = 5.', 'Resta x: x + 3 = 8. Resta 3: x = 5.', 'Odejmij x: x + 3 = 8. Odejmij 3: x = 5.'),
      workedSolutionLatex: '2x+3=x+8 \\Rightarrow x+3=8 \\Rightarrow x=5',
      standards: stdBoth,
      irtPriors: { a: 1, b: -0.8 },
      difficulty: 'intro',
    },
    {
      id: 'item.ido.2',
      kpIds: ['kp.equation.both-sides-isolate'],
      phase: 'i_do',
      type: 'mcq',
      stem: L('Solve: $5x - 1 = 2x + 11$', 'Resuelve: $5x - 1 = 2x + 11$', 'Rozwiąż: $5x - 1 = 2x + 11$'),
      stemLatex: '5x - 1 = 2x + 11',
      choices: [
        choice('a', 'x = 4', true, undefined, L('Correct: subtract 2x → 3x − 1 = 11 → 3x = 12 → x = 4.', 'Correcto: resta 2x → 3x − 1 = 11 → 3x = 12 → x = 4.', 'Poprawnie: odejmij 2x → 3x − 1 = 11 → 3x = 12 → x = 4.')),
        choice('b', 'x = 12', false, 'partial-solve', L('3x = 12 is only the middle step — divide by 3.', '3x = 12 es solo el paso intermedio — divide entre 3.', '3x = 12 to tylko krok pośredni — podziel przez 3.')),
        choice('c', 'x = 3', false, 'wrong-inverse', L('11 − 1 = 10 is wrong: undo −1 by adding 1 → 11 + 1 = 12.', '11 − 1 = 10 es incorrecto: deshaz −1 sumando 1 → 12.', '11 − 1 = 10 jest złe: cofnij −1 dodając 1 → 12.')),
        choice('d', 'x = 2', false, 'wrong-side', L('Subtracting 5x instead of 2x flips the variable side incorrectly.', 'Restar 5x en vez de 2x invierte mal el lado de la variable.', 'Odejmowanie 5x zamiast 2x źle odwraca stronę zmiennej.')),
      ],
      workedSolution: L('Subtract 2x: 3x − 1 = 11. Add 1: 3x = 12. Divide by 3: x = 4.', 'Resta 2x: 3x − 1 = 11. Suma 1: 3x = 12. Divide entre 3: x = 4.', 'Odejmij 2x: 3x − 1 = 11. Dodaj 1: 3x = 12. Podziel przez 3: x = 4.'),
      workedSolutionLatex: '5x-1=2x+11 \\Rightarrow 3x-1=11 \\Rightarrow 3x=12 \\Rightarrow x=4',
      standards: stdBoth,
      irtPriors: { a: 1, b: -0.5 },
      difficulty: 'intro',
    },
    {
      id: 'item.wedo.1',
      kpIds: ['kp.equation.both-sides-collect'],
      phase: 'we_do',
      type: 'short',
      stem: L('Solve for x: $3x + 7 = x + 19$. Enter the value of x.', 'Despeja x: $3x + 7 = x + 19$. Escribe el valor de x.', 'Rozwiąż x: $3x + 7 = x + 19$. Wpisz wartość x.'),
      stemLatex: '3x + 7 = x + 19',
      answer: 6,
      acceptableAnswers: ['6', 'x=6', 'x = 6'],
      workedSolution: L('Subtract x: 2x + 7 = 19. Subtract 7: 2x = 12. Divide by 2: x = 6.', 'Resta x: 2x + 7 = 19. Resta 7: 2x = 12. Divide entre 2: x = 6.', 'Odejmij x: 2x + 7 = 19. Odejmij 7: 2x = 12. Podziel przez 2: x = 6.'),
      workedSolutionLatex: '3x+7=x+19 \\Rightarrow 2x+7=19 \\Rightarrow 2x=12 \\Rightarrow x=6',
      standards: stdBoth,
      irtPriors: { a: 1, b: -0.3 },
      difficulty: 'guided',
    },
    {
      id: 'item.wedo.2',
      kpIds: ['kp.equation.both-sides-isolate'],
      phase: 'we_do',
      type: 'mcq',
      stem: L('Solve: $4x - 5 = x + 16$', 'Resuelve: $4x - 5 = x + 16$', 'Rozwiąż: $4x - 5 = x + 16$'),
      stemLatex: '4x - 5 = x + 16',
      choices: [
        choice('a', 'x = 21', false, 'partial-solve', L('3x = 21 is the middle — divide by 3 to get 7.', '3x = 21 es el medio — divide entre 3 para obtener 7.', '3x = 21 to środek — podziel przez 3, by dostać 7.')),
        choice('b', 'x = 7', true, undefined, L('Correct: subtract x → 3x − 5 = 16 → 3x = 21 → x = 7.', 'Correcto: resta x → 3x − 5 = 16 → 3x = 21 → x = 7.', 'Poprawnie: odejmij x → 3x − 5 = 16 → 3x = 21 → x = 7.')),
        choice('c', 'x = 11/3', false, 'wrong-inverse', L('16 − 5 undoes nothing useful; add 5 to both sides after collecting.', '16 − 5 no deshace nada útil; suma 5 tras reunir.', '16 − 5 nic nie cofa; dodaj 5 po zebraniu.')),
        choice('d', 'x = 5', false, 'wrong-side', L('Mixing constants with the wrong collect path.', 'Mezclas constantes con una reunión incorrecta.', 'Mieszasz stałe ze złą ścieżką zbierania.')),
      ],
      workedSolution: L('Subtract x: 3x − 5 = 16. Add 5: 3x = 21. Divide by 3: x = 7.', 'Resta x: 3x − 5 = 16. Suma 5: 3x = 21. Divide entre 3: x = 7.', 'Odejmij x: 3x − 5 = 16. Dodaj 5: 3x = 21. Podziel przez 3: x = 7.'),
      workedSolutionLatex: '4x-5=x+16 \\Rightarrow 3x-5=16 \\Rightarrow 3x=21 \\Rightarrow x=7',
      standards: stdBoth,
      irtPriors: { a: 1, b: -0.1 },
      difficulty: 'guided',
    },
    {
      id: 'item.wedo.3',
      kpIds: ['kp.equation.both-sides-signed'],
      phase: 'we_do',
      type: 'mcq',
      stem: L('Solve: $-2x + 9 = 3x - 6$', 'Resuelve: $-2x + 9 = 3x - 6$', 'Rozwiąż: $-2x + 9 = 3x - 6$'),
      stemLatex: '-2x + 9 = 3x - 6',
      choices: [
        choice('a', 'x = -3', false, 'sign-slip', L('Sign slip when collecting: subtracting 3x from −2x gives −5x, not +x.', 'Error de signo al reunir: restar 3x de −2x da −5x, no +x.', 'Pomyłka znaku: odejmowanie 3x od −2x daje −5x, nie +x.')),
        choice('b', 'x = 15', false, 'partial-solve', L('−5x = −15 is only the middle — divide by −5.', '−5x = −15 es solo el medio — divide entre −5.', '−5x = −15 to tylko środek — podziel przez −5.')),
        choice('c', 'x = 3', true, undefined, L('Correct: subtract 3x → −5x + 9 = −6 → −5x = −15 → x = 3.', 'Correcto: resta 3x → −5x + 9 = −6 → −5x = −15 → x = 3.', 'Poprawnie: odejmij 3x → −5x + 9 = −6 → −5x = −15 → x = 3.')),
        choice('d', 'x = -15', false, 'wrong-inverse', L('Reporting the RHS intermediate as the answer after −5x = −15.', 'Reportar el intermedio RHS como respuesta tras −5x = −15.', 'Podanie pośredniego RHS jako odpowiedzi po −5x = −15.')),
      ],
      workedSolution: L('Subtract 3x: −5x + 9 = −6. Subtract 9: −5x = −15. Divide by −5: x = 3.', 'Resta 3x: −5x + 9 = −6. Resta 9: −5x = −15. Divide entre −5: x = 3.', 'Odejmij 3x: −5x + 9 = −6. Odejmij 9: −5x = −15. Podziel przez −5: x = 3.'),
      workedSolutionLatex: '-2x+9=3x-6 \\Rightarrow -5x+9=-6 \\Rightarrow -5x=-15 \\Rightarrow x=3',
      standards: stdBoth,
      irtPriors: { a: 1, b: 0.2 },
      difficulty: 'guided',
    },
    {
      id: 'item.wedo.4',
      kpIds: ['kp.equation.both-sides-signed'],
      phase: 'we_do',
      type: 'short',
      stem: L('Solve for x: $5 - 2x = x + 14$. Enter the value of x.', 'Despeja x: $5 - 2x = x + 14$. Escribe el valor de x.', 'Rozwiąż x: $5 - 2x = x + 14$. Wpisz wartość x.'),
      stemLatex: '5 - 2x = x + 14',
      answer: -3,
      acceptableAnswers: ['-3', 'x=-3', 'x = -3'],
      workedSolution: L('Subtract x: 5 − 3x = 14. Subtract 5: −3x = 9. Divide by −3: x = −3.', 'Resta x: 5 − 3x = 14. Resta 5: −3x = 9. Divide entre −3: x = −3.', 'Odejmij x: 5 − 3x = 14. Odejmij 5: −3x = 9. Podziel przez −3: x = −3.'),
      workedSolutionLatex: '5-2x=x+14 \\Rightarrow 5-3x=14 \\Rightarrow -3x=9 \\Rightarrow x=-3',
      standards: stdBoth,
      irtPriors: { a: 1, b: 0.35 },
      difficulty: 'guided',
    },
    {
      id: 'item.youdo.1',
      kpIds: ['kp.equation.both-sides-collect'],
      phase: 'you_do',
      type: 'mcq',
      stem: L('Solve: $5x + 2 = 2x + 26$', 'Resuelve: $5x + 2 = 2x + 26$', 'Rozwiąż: $5x + 2 = 2x + 26$'),
      stemLatex: '5x + 2 = 2x + 26',
      choices: [
        choice('a', 'x = 28', false, 'wrong-inverse', L('Adding constants without collecting variables first.', 'Sumar constantes sin reunir variables primero.', 'Dodawanie stałych bez wcześniejszego zbierania zmiennych.')),
        choice('b', 'x = 24', false, 'partial-solve', L('3x = 24 is the middle step — divide by 3.', '3x = 24 es el paso intermedio — divide entre 3.', '3x = 24 to krok pośredni — podziel przez 3.')),
        choice('c', 'x = 6', false, 'wrong-side', L('Subtracting 5x from both sides leaves a negative path to a different value.', 'Restar 5x en ambos lados deja una ruta negativa a otro valor.', 'Odejmowanie 5x po obu stronach daje inną wartość.')),
        choice('d', 'x = 8', true, undefined, L('Correct: subtract 2x → 3x + 2 = 26 → 3x = 24 → x = 8.', 'Correcto: resta 2x → 3x + 2 = 26 → 3x = 24 → x = 8.', 'Poprawnie: odejmij 2x → 3x + 2 = 26 → 3x = 24 → x = 8.')),
      ],
      workedSolution: L('Subtract 2x: 3x + 2 = 26. Subtract 2: 3x = 24. Divide by 3: x = 8.', 'Resta 2x: 3x + 2 = 26. Resta 2: 3x = 24. Divide entre 3: x = 8.', 'Odejmij 2x: 3x + 2 = 26. Odejmij 2: 3x = 24. Podziel przez 3: x = 8.'),
      workedSolutionLatex: '5x+2=2x+26 \\Rightarrow 3x+2=26 \\Rightarrow 3x=24 \\Rightarrow x=8',
      standards: stdBoth,
      irtPriors: { a: 1, b: 0.3 },
      difficulty: 'independent',
    },
    {
      id: 'item.youdo.2',
      kpIds: ['kp.equation.both-sides-isolate'],
      phase: 'you_do',
      type: 'mcq',
      stem: L('Solve: $6x - 4 = 3x + 2$', 'Resuelve: $6x - 4 = 3x + 2$', 'Rozwiąż: $6x - 4 = 3x + 2$'),
      stemLatex: '6x - 4 = 3x + 2',
      choices: [
        choice('a', 'x = 2', true, undefined, L('Correct: subtract 3x → 3x − 4 = 2 → 3x = 6 → x = 2.', 'Correcto: resta 3x → 3x − 4 = 2 → 3x = 6 → x = 2.', 'Poprawnie: odejmij 3x → 3x − 4 = 2 → 3x = 6 → x = 2.')),
        choice('b', 'x = 6', false, 'partial-solve', L('3x = 6 still needs dividing by 3.', '3x = 6 aún necesita dividir entre 3.', '3x = 6 nadal wymaga dzielenia przez 3.')),
        choice('c', 'x = -2', false, 'sign-slip', L('Sign slip when moving the constant −4.', 'Error de signo al mover la constante −4.', 'Pomyłka znaku przy przenoszeniu stałej −4.')),
        choice('d', 'x = 2/3', false, 'wrong-inverse', L('Dividing before adding 4 to both sides.', 'Dividir antes de sumar 4 en ambos lados.', 'Dzielenie przed dodaniem 4 po obu stronach.')),
      ],
      workedSolution: L('Subtract 3x: 3x − 4 = 2. Add 4: 3x = 6. Divide by 3: x = 2.', 'Resta 3x: 3x − 4 = 2. Suma 4: 3x = 6. Divide entre 3: x = 2.', 'Odejmij 3x: 3x − 4 = 2. Dodaj 4: 3x = 6. Podziel przez 3: x = 2.'),
      workedSolutionLatex: '6x-4=3x+2 \\Rightarrow 3x-4=2 \\Rightarrow 3x=6 \\Rightarrow x=2',
      standards: stdBoth,
      irtPriors: { a: 1, b: 0.45 },
      difficulty: 'independent',
    },
    {
      id: 'item.youdo.3',
      kpIds: ['kp.equation.both-sides-signed'],
      phase: 'you_do',
      type: 'mcq',
      stem: L('Solve: $-3x + 5 = x + 13$', 'Resuelve: $-3x + 5 = x + 13$', 'Rozwiąż: $-3x + 5 = x + 13$'),
      stemLatex: '-3x + 5 = x + 13',
      choices: [
        choice('a', 'x = 2', false, 'sign-slip', L('Lost the negative: −4x = 8 → x = −2, not +2.', 'Se perdió el negativo: −4x = 8 → x = −2, no +2.', 'Zagubiono minus: −4x = 8 → x = −2, nie +2.')),
        choice('b', 'x = -2', true, undefined, L('Correct: subtract x → −4x + 5 = 13 → −4x = 8 → x = −2.', 'Correcto: resta x → −4x + 5 = 13 → −4x = 8 → x = −2.', 'Poprawnie: odejmij x → −4x + 5 = 13 → −4x = 8 → x = −2.')),
        choice('c', 'x = 8', false, 'partial-solve', L('−4x = 8 is intermediate — divide by −4.', '−4x = 8 es intermedio — divide entre −4.', '−4x = 8 jest pośrednie — podziel przez −4.')),
        choice('d', 'x = -8', false, 'wrong-inverse', L('Subtracting 5 from 13 with a sign flip error on the variable side.', 'Restar 5 de 13 con error de signo en el lado de la variable.', 'Odejmowanie 5 od 13 z błędem znaku po stronie zmiennej.')),
      ],
      workedSolution: L('Subtract x: −4x + 5 = 13. Subtract 5: −4x = 8. Divide by −4: x = −2.', 'Resta x: −4x + 5 = 13. Resta 5: −4x = 8. Divide entre −4: x = −2.', 'Odejmij x: −4x + 5 = 13. Odejmij 5: −4x = 8. Podziel przez −4: x = −2.'),
      workedSolutionLatex: '-3x+5=x+13 \\Rightarrow -4x+5=13 \\Rightarrow -4x=8 \\Rightarrow x=-2',
      standards: stdBoth,
      irtPriors: { a: 1, b: 0.55 },
      difficulty: 'independent',
    },
    {
      id: 'item.youdo.4',
      kpIds: ['kp.equation.both-sides-verify'],
      phase: 'you_do',
      type: 'mcq',
      stem: L(
        'Which value of x makes both sides of $2x + 5 = x + 14$ equal?',
        '¿Qué valor de x hace iguales ambos lados de $2x + 5 = x + 14$?',
        'Która wartość x sprawia, że obie strony $2x + 5 = x + 14$ są równe?',
      ),
      stemLatex: '2x + 5 = x + 14',
      choices: [
        choice('a', 'x = 5', false, 'verify-skip', L('2(5)+5=15 but 5+14=19 — sides do not match.', '2(5)+5=15 pero 5+14=19 — no coinciden.', '2(5)+5=15, ale 5+14=19 — strony się nie zgadzają.')),
        choice('b', 'x = 14', false, 'verify-skip', L('2(14)+5=33 but 14+14=28 — not equal.', '2(14)+5=33 pero 14+14=28 — no iguales.', '2(14)+5=33, ale 14+14=28 — nierówne.')),
        choice('c', 'x = 9', true, undefined, L('Correct: 2(9)+5=23 and 9+14=23 — both sides match.', 'Correcto: 2(9)+5=23 y 9+14=23 — coinciden.', 'Poprawnie: 2(9)+5=23 i 9+14=23 — obie strony się zgadzają.')),
        choice('d', 'x = 4', false, 'verify-skip', L('2(4)+5=13 but 4+14=18 — not a solution.', '2(4)+5=13 pero 4+14=18 — no es solución.', '2(4)+5=13, ale 4+14=18 — to nie rozwiązanie.')),
      ],
      workedSolution: L('Solve: subtract x → x + 5 = 14 → x = 9. Check: 2(9)+5=23, 9+14=23.', 'Resuelve: resta x → x + 5 = 14 → x = 9. Comprueba: 2(9)+5=23, 9+14=23.', 'Rozwiąż: odejmij x → x + 5 = 14 → x = 9. Sprawdź: 2(9)+5=23, 9+14=23.'),
      workedSolutionLatex: '2x+5=x+14 \\Rightarrow x+5=14 \\Rightarrow x=9;\\; 2(9)+5=23=9+14',
      standards: stdVerify,
      irtPriors: { a: 1, b: 0.7 },
      difficulty: 'independent',
    },
    {
      id: 'item.retr.1',
      kpIds: ['kp.equation.both-sides-isolate'],
      phase: 'retrieval',
      type: 'mcq',
      stem: L('Solve: $4x + 1 = 2x + 21$', 'Resuelve: $4x + 1 = 2x + 21$', 'Rozwiąż: $4x + 1 = 2x + 21$'),
      stemLatex: '4x + 1 = 2x + 21',
      choices: [
        choice('a', 'x = 10', true, undefined, L('Correct: subtract 2x → 2x + 1 = 21 → 2x = 20 → x = 10.', 'Correcto: resta 2x → 2x + 1 = 21 → 2x = 20 → x = 10.', 'Poprawnie: odejmij 2x → 2x + 1 = 21 → 2x = 20 → x = 10.')),
        choice('b', 'x = 20', false, 'partial-solve', L('2x = 20 still needs ÷ 2.', '2x = 20 aún necesita ÷ 2.', '2x = 20 nadal wymaga ÷ 2.')),
        choice('c', 'x = 11', false, 'wrong-inverse', L('Adding 1 to 21 without collecting first.', 'Sumar 1 a 21 sin reunir primero.', 'Dodanie 1 do 21 bez wcześniejszego zbierania.')),
        choice('d', 'x = 5', false, 'wrong-side', L('Halving too early after a wrong collect.', 'Dividir a la mitad demasiado pronto tras una reunión incorrecta.', 'Dzielenie na pół zbyt wcześnie po złym zebraniu.')),
      ],
      workedSolution: L('Subtract 2x: 2x + 1 = 21. Subtract 1: 2x = 20. Divide by 2: x = 10.', 'Resta 2x: 2x + 1 = 21. Resta 1: 2x = 20. Divide entre 2: x = 10.', 'Odejmij 2x: 2x + 1 = 21. Odejmij 1: 2x = 20. Podziel przez 2: x = 10.'),
      workedSolutionLatex: '4x+1=2x+21 \\Rightarrow 2x+1=21 \\Rightarrow 2x=20 \\Rightarrow x=10',
      standards: stdBoth,
      irtPriors: { a: 1, b: -1.0 },
      difficulty: 'intro',
    },
    {
      id: 'item.retr.2',
      kpIds: ['kp.equation.both-sides-signed'],
      phase: 'retrieval',
      type: 'evaluate',
      stem: L('Solve for x: $3 - 2x = x + 15$. Enter x.', 'Despeja x: $3 - 2x = x + 15$. Escribe x.', 'Rozwiąż x: $3 - 2x = x + 15$. Wpisz x.'),
      stemLatex: '3 - 2x = x + 15',
      answer: -4,
      acceptableAnswers: ['-4', 'x=-4', 'x = -4'],
      choices: [
        choice('a', '-4', true, undefined, L('Correct.', 'Correcto.', 'Poprawnie.')),
        choice('b', '4', false, 'sign-slip', L('Sign slip after −3x = −12.', 'Error de signo tras −3x = −12.', 'Pomyłka znaku po −3x = −12.')),
        choice('c', '-12', false, 'partial-solve', L('Intermediate RHS reported early.', 'RHS intermedio reportado pronto.', 'Wczesne podanie pośredniego RHS.')),
        choice('d', '6', false, 'wrong-inverse', L('Wrong inverse on the constants.', 'Inverso incorrecto en las constantes.', 'Zła operacja odwrotna na stałych.')),
      ],
      workedSolution: L('Subtract x: 3 − 3x = 15. Subtract 3: −3x = 12. Divide by −3: x = −4.', 'Resta x: 3 − 3x = 15. Resta 3: −3x = 12. Divide entre −3: x = −4.', 'Odejmij x: 3 − 3x = 15. Odejmij 3: −3x = 12. Podziel przez −3: x = −4.'),
      workedSolutionLatex: '3-2x=x+15 \\Rightarrow 3-3x=15 \\Rightarrow -3x=12 \\Rightarrow x=-4',
      standards: stdBoth,
      irtPriors: { a: 1, b: -0.6 },
      difficulty: 'intro',
    },
  ],
  mastery: {
    minIndependentCorrect: 3,
    minIndependentTotal: 4,
    requiredKpIds: [
      'kp.equation.both-sides-collect',
      'kp.equation.both-sides-isolate',
      'kp.equation.both-sides-signed',
      'kp.equation.both-sides-verify',
    ],
  },
  unlocks: [
    {
      id: 'bp.balance.mirror',
      kind: 'blueprint',
      title: L('Mirror beam blueprint', 'Plano de viga espejo', 'Plan belki lustrzanej'),
      description: L(
        'A both-sides mirror beam — earned by collecting variable terms across the equals sign.',
        'Una viga espejo de ambos lados — ganada al reunir términos con variable a través del igual.',
        'Belka lustrzana obu stron — zdobyta przez zbieranie wyrazów ze zmienną przez znak równości.',
      ),
    },
    {
      id: 'rank.riser.vanguard',
      kind: 'rank',
      title: L('Riser Vanguard', 'Ascendente Vanguardia', 'Wznoszący Awangarda'),
      description: L(
        'Sixth rung of the Riser ladder, earned by Lesson 6 mastery.',
        'Sexto peldaño de la escalera del Ascendente, ganado con el dominio de la Lección 6.',
        'Szósty szczebel drabiny Wznoszącego, zdobyty mistrzostwem Lekcji 6.',
      ),
    },
    {
      id: 'zone.zeta.mirror',
      kind: 'zone',
      title: L('Zeta Mirror Yard', 'Patio Espejo Zeta', 'Dziedziniec Lustra Zeta'),
      description: L(
        'A mirror yard where both-sides equations are balanced before forge duty.',
        'Un patio espejo donde se equilibran ecuaciones de ambos lados antes del servicio de forja.',
        'Dziedziniec lustrzany, gdzie równania obu stron są równoważone przed służbą kuźni.',
      ),
    },
  ],
  worldIntegration: {
    terminalId: 'terminal.lesson6',
    unlockBlueprintId: 'bp.balance.mirror',
    unlockRankId: 'rank.riser.vanguard',
    unlockZoneId: 'zone.zeta.mirror',
  },
  _pipelineMeta: {
    stage: 'Integration (authored by builder wave 26)',
    generatedAt: '2026-08-05T15:00:00.000Z',
    notes: [
      'Variables on both sides after L5 two-step; fourth KP is verify-by-substitution.',
      'Cross-lesson prereqs from algebra-i-05 two-step KPs.',
      'Answer keys distinct: 5,4,6,7,3,-3,8,2,-2,9,10,-4. MCQ correct positions mixed (c,a,b,c,d,a,b,c,a).',
      'GameView 3D props deferred (wave-25 owns L5 props in parallel).',
    ],
  },
}

mkdirSync(dirname(outPath), { recursive: true })
writeFileSync(outPath, JSON.stringify(pkg, null, 2) + '\n', 'utf8')
console.log('Wrote', outPath)
